// src/components/NavBar.vue
<template>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
    <div class="container">
      <a href="#top" class="navbar-brand"
        ><span class="fw-lighter">Jack</span><span class="fw-bold">Koskie</span></a
      >
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle Navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item"><a href="#top" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="#contact" class="nav-link">Contact Me</a></li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<script setup></script>

<style lang="scss" scoped></style>

// src/routes/Navbar.svelte
<nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
	<div class="container">
		<a href="#top" class="navbar-brand"
			><span class="fw-lighter">Jack</span><span class="fw-bold">Koskie</span></a
		>
		<button
			class="navbar-toggler"
			type="button"
			data-bs-toggle="collapse"
			data-bs-target="#navbarNav"
			aria-controls="navbarNav"
			aria-expanded="false"
			aria-label="Toggle navigation"
		>
			<span class="navbar-toggler-icon" />
		</button>
		<div class="navbar-collapse collapse" id="navbarNav">
			<ul class="navbar-nav">
				<li class="nav-item"><a href="/" class="nav-link">Home</a></li>
			</ul>
		</div>
	</div>
</nav>
